apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  
  # Mysql Parameters
  MYSQL_ROOT_PASSWORD: {{ .Values.rootpassword }}
  MYSQL_DATABASE: {{ .Values.dbname }}
  MYSQL_USER: {{ .Values.mysqluser }}
  MYSQL_PASSWORD: {{ .Values.mysqlpassword }}
  # Email Parameters
  # - the hostname/IP address of your mailserver
  MAIL_PORT_587_TCP_ADDR: {{ .Values.mailserver }}
  #the port for the mailserver (probably 587, could be another)
  MAIL_PORT_587_TCP_PORT: {{ .Values.port }}
  # the default from address, and from name for emails
  MAIL_ENV_FROM_ADDR: {{ .Values.address }}
  MAIL_ENV_FROM_NAME: {{ .Values.fromname }}
  # - pick 'tls' for SMTP-over-SSL, 'tcp' for unencrypted
  MAIL_ENV_ENCRYPTION: {{ .Values.encryption }}
  # SMTP username and password
  MAIL_ENV_USERNAME: {{ .Values.fromemail }}
  MAIL_ENV_PASSWORD=: {{ .Values.emailpw }}
  # Snipe-IT Settings
  APP_ENV: {{ .Values.env }}
  APP_DEBUG: {{ .Values.debugsetting }}
  APP_KEY: {{ .Values.appkey }}
  APP_URL: {{ .Values.appurl }}
  APP_TIMEZONE: {{ .Values.timezone }}
  APP_LOCALE: {{ .Values.language }}
